import type { Metadata } from "next";
import "./globals.css";
import { SettingsProvider } from './contexts/SettingsContext';


export const metadata: Metadata = {
  title: "Spring Hack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=DotGothic16&display=swap"
          rel="stylesheet"
        />
      </head>
      <body><SettingsProvider>
          {children}
        </SettingsProvider></body>
    </html>
  );
}